### ISSUE TITLE
Media references are not resolved

### ISSUE THREAD

**Issue by tgrassl** [e-Spirit/fsxa-api#11]
Hi, we currently face the issue that some media references have the wrong type and are missing the resolutions object.

Wrong mapping:
```javascript
...
    fsType: "FS_REFERENCE",
    name: "linktmpl_image",
    value: {
      fsType: "Media",
      identifier: "108ff4b0-c6c0-432f-8524-954b1f760b80",
      mediaType: "PICTURE",
      name: "siegel_bester_baufinanzierer_08_2017",
      uid: "siegel_bester_baufinanzierer_08_2017",
      uidType: "MEDIASTORE_LEAF",
      url: ".../0bf5e07a-2910-4a6d-bade-b4cff019db27.preview.content/108ff4b0-c6c0-432f-8524-954b1f760b80.de_DE"
    }
...
```

Correct mapping:
```javascript
...
{
   id: "f058b0c8-1fe1-4da9-bf89-76347f7623d0",
   previewId: "f058b0c8-1fe1-4da9-bf89-76347f7623d0.de_DE",
   meta":{
      
   },
   description: null,
   resolutions: {
      "5050DesktopNormal":{
         "fileSize":239513,
         "extension":"png",
         "mimeType":"image/png",
         "width":450,
         "height":454,
         "url":".../0bf5e07a-2910-4a6d-bade-b4cff019db27.preview.files/f058b0c8-1fe1-4da9-bf89-76347f7623d0.5050DesktopNormal/binary"
      },
...
```

Both have the same initial json structure in the CaaS.

@tgolbs Is there a specific reason for this behaviour or is this a mapping bug?

**Comment by tgolbs** [comment]
@tgrassl Where are the wrong mappings embedded? Is this referenced in RichText or custom elements, where the automatic mapping and resolving mechanism is not configured for?

**Comment by tgrassl** [comment]
@tgolbs Both are inside a FS_CATALOG Card template

**Comment by tgolbs** [comment]
And the FS_CATALOG is located directly under data or are there other parent nodes? Then it may be that one of them is not mapped. Because the "wrong" mapping format looks to me just like the original format. Is the FS_CATALOG located in a RichText JSON?

**Comment by tgrassl** [comment]
Ok, yes the "wrong" mapping is inside a nested FS_CATALOG for a group where each group card also has a child catalog

**Comment by tgrassl** [comment]
Looks like the issue is the page type. The page has the fstype ProjectProperties and is not mapped by CaasMapper

**Comment by tgolbs** [comment]
Ok, that is vital information. We are currently looking over this [Pull Request](https://github.com/e-Spirit/fsxa-api/pull/10). It will enable automatic mapping for Pages with the type ```ProjectProperties```. When this is merged your Page should be mapped automatically.

**Comment by tgrassl** [comment]
Nice, that would be awesome to get merged soon 👍
