### ISSUE TITLE
CaasMapper provides unconsistent types for table cell colspan and rowspan

### ISSUE THREAD

**Issue by alexkoerner** [e-Spirit/fsxa-api#129]
The structure for a table contains the type `number` in the colspan and in the rowspan key if the value is `1`. Otherwise the value is from type `string`.

**Comment by henczi-espirit** [comment]
This issue seems to be related to #128.
We will treat both issues as one and update on the earlier report. 
>> closed

**Comment by henczi-espirit** [comment]
It turns out that issue https://github.com/e-Spirit/fsxa-api/issues/128 and this one here are not related. @alexkoerner could you provide a reproduction for a scenario where this typing issue leads to a problem or is it a typing issue without any further impact?

**Comment by alexkoerner** [comment]
I don't know what has been changed in the background, but the values are now typed correct as number.

**Comment by henczi-espirit** [comment]
That is good. I will close the issue :-)
