### ISSUE TITLE
CaaSMapper: FS_Catalog with template type link maps to Section instead of Link

### ISSUE THREAD

**Issue by ls-espirit** [e-Spirit/fsxa-api#29]
Hello,

Given an FS_Catalog with Section type="link", e.g.

```

   <FS_CATALOG name="st_linkList">
     <LANGINFOS>
       <LANGINFO lang="*" label="Linklist"/>
     </LANGINFOS>
     <TEMPLATES type="link">
       <TEMPLATE uid="external_link"/>
       <TEMPLATE uid="internal_link"/>
     </TEMPLATES>
   </FS_CATALOG>
```

  
  The expectation would be to find a List of Elements that correspond to a normal CMS_INPUT_LINK
Instead, Links are mapped as if they were Sections. 

See CMS_INPUT_LINK:
https://github.com/e-Spirit/fsxa-api/blob/61cc5c96a57c895eb05f238701c7ba4330096879/src/modules/CaaSMapper.ts#L101

And Catalog Mapping
https://github.com/e-Spirit/fsxa-api/blob/61cc5c96a57c895eb05f238701c7ba4330096879/src/modules/CaaSMapper.ts#L136

Der (simple) Fix dieses Problems ist leider ein breaking Change

**Comment by dbarczewski** [comment]
Thank you for opening this issue. 

We are planning to release a new major version and this could be included there as well. 

Do you think you could open a PR to merge this change in the `alpha`-branch?

That would be great!

**Comment by henczi-espirit** [comment]
@ls-espirit if this is still an issue for you, it would be nice if you would open up a Jira ticket 😄
