### ISSUE TITLE
Readme does not match released version

### ISSUE THREAD

**Issue by tk127** [e-Spirit/fsxa-api#71]
The documentation on how to use the fsxa-api is outdated since the release of v6.0.0 as it still uses the FSXAApi class and the old parameters on fetchByFilter, ...

e.g.:
`const remoteApi = new FSXAApi(
FSXAContentMode.PREVIEW,
...`
in
https://github.com/e-Spirit/fsxa-api/blob/358f1d65ed8a7d5f262b281e3731c510dadbabe5/README.md?plain=1#L131

**Comment by henczi-espirit** [comment]
Thank you for opening issue.
The team is committed to updating the outdated documentation next. The topic is prioritized.

**Comment by henczi-espirit** [comment]
Documentation change has been rolled out.
