### ISSUE TITLE
XML Parser maps div to wrong paragraph type

### ISSUE THREAD

**Issue by tgrassl** [e-Spirit/fsxa-api#8]
A div should not be treated like a paragraph tag and instead be mapped to it's own type e.g. "block":

```javascript
...
      case 'p':
        return {
          data: tag.attributes,
          content: [],
          type: 'paragraph'
        }
      case 'div':
        return {
          data: tag.attributes,
          content: [],
          type: 'block'
        }
...
```

instead of

```javascript
...
      case 'p':
      case 'div':
        return {
          data: tag.attributes,
          content: [],
          type: 'paragraph'
        }
...
```

This currently leads to a mapping issue in our RichText Component because we can only wrap content in p tags instead of the correct div tag.

**Comment by maidi29** [comment]
@tgolbs could you take a look at this pull request? It would really help us because right now every CMS_INPUT_DOM is wrapped by <p> tags what results in lots of errors because some other tags can't be children of <p> tags  :)

**Comment by tgolbs** [comment]
Thank you for your work. I've merged your PR.
